"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/building.glb --types 
*/
// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    building1: THREE.Mesh;
    building9_1: THREE.Mesh;
    building9_2: THREE.Mesh;
    building4_1: THREE.Mesh;
    building4_2: THREE.Mesh;
    building3_1: THREE.Mesh;
    building3_2: THREE.Mesh;
    building5: THREE.Mesh;
    building40_1: THREE.Mesh;
    building40_2: THREE.Mesh;
    building6_1: THREE.Mesh;
    building6_2: THREE.Mesh;
    building7_1: THREE.Mesh;
    building7_2: THREE.Mesh;
    building12_1: THREE.Mesh;
    building12_2: THREE.Mesh;
    building13: THREE.Mesh;
    building14: THREE.Mesh;
    building15_1: THREE.Mesh;
    building15_2: THREE.Mesh;
    building16_1: THREE.Mesh;
    building16_2: THREE.Mesh;
    building19_1: THREE.Mesh;
    building19_2: THREE.Mesh;
    building21_1: THREE.Mesh;
    building21_2: THREE.Mesh;
    building18_1: THREE.Mesh;
    building18_2: THREE.Mesh;
    building20_1: THREE.Mesh;
    building20_2: THREE.Mesh;
    building22_1: THREE.Mesh;
    building22_2: THREE.Mesh;
    building23_1: THREE.Mesh;
    building23_2: THREE.Mesh;
    building25_1: THREE.Mesh;
    building25_2: THREE.Mesh;
    building26_1: THREE.Mesh;
    building26_2: THREE.Mesh;
    building10: THREE.Mesh;
    wood_bars: THREE.Mesh;
    rails11: THREE.Mesh;
    rails8: THREE.Mesh;
    rails1: THREE.Mesh;
    rails2: THREE.Mesh;
    rails5: THREE.Mesh;
    rails6: THREE.Mesh;
    rails7: THREE.Mesh;
    rails9: THREE.Mesh;
    rails10: THREE.Mesh;
    rails12: THREE.Mesh;
    wood: THREE.Mesh;
  };
  materials: {
    ["Wood Wall Slits Variation 2"]: THREE.MeshStandardMaterial;
    stone: THREE.MeshStandardMaterial;
    ["plaster white irregular"]: THREE.MeshStandardMaterial;
    ["Metal Semirough 01"]: THREE.MeshStandardMaterial;
    ["EEVEE Glass Shader"]: THREE.MeshStandardMaterial;
    ["Metal Semirough 01"]: THREE.MeshStandardMaterial;
    ["EEVEE Glass Shader.001"]: THREE.MeshStandardMaterial;
    ["plaster white irregular"]: THREE.MeshStandardMaterial;
  };
};

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Building(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/building.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.building1.geometry}
        material={materials["Wood Wall Slits Variation 2"]}
        position={[0, 9.95, 0]}
        scale={[4, 1.65, 5]}
      />
      <group
        position={[1, 6.65, -1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[4, 1.65, 5]}
      >
        <mesh
          geometry={nodes.building9_1.geometry}
          material={materials.stone}
        />
        <mesh
          geometry={nodes.building9_2.geometry}
          material={materials["plaster white irregular"]}
        />
      </group>
      <group position={[0, 8.3, 0]}>
        <mesh
          geometry={nodes.building4_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building4_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[2.013, 4.943, -2.022]}>
        <mesh
          geometry={nodes.building3_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building3_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <mesh
        geometry={nodes.building5.geometry}
        material={materials["Wood Wall Slits Variation 2"]}
        position={[0, 16.55, 0]}
        scale={[4, 1.65, 5]}
      />
      <group
        position={[1, 13.25, -1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[4, 1.65, 5]}
      >
        <mesh
          geometry={nodes.building40_1.geometry}
          material={materials.stone}
        />
        <mesh
          geometry={nodes.building40_2.geometry}
          material={materials["plaster white irregular"]}
        />
      </group>
      <group position={[0, 14.9, 0]}>
        <mesh
          geometry={nodes.building6_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building6_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[2.013, 11.543, -2.022]}>
        <mesh
          geometry={nodes.building7_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building7_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[0, 1, 0]}>
        <mesh
          geometry={nodes.building12_1.geometry}
          material={materials.stone}
        />
        <mesh
          geometry={nodes.building12_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <mesh
        geometry={nodes.building13.geometry}
        material={materials["plaster white irregular"]}
      />
      <mesh geometry={nodes.building14.geometry} material={materials.stone} />
      <group position={[0, 1, -0.048]}>
        <mesh
          geometry={nodes.building15_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building15_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[0, 7.6, -0.048]}>
        <mesh
          geometry={nodes.building16_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building16_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[-7.01, 4.3, 7.947]}>
        <mesh
          geometry={nodes.building19_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building19_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[-7.01, -2.3, 7.947]}>
        <mesh
          geometry={nodes.building21_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building21_2.geometry}
          material={materials["EEVEE Glass Shader"]}
        />
      </group>
      <group position={[7.164, 1.307, 2.556]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.building18_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building18_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group position={[7.164, 1.307, -2.092]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.building20_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building20_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group position={[7.164, 1.307, -6.739]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.building22_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building22_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group position={[7.164, 1.307, -11.387]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.building23_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building23_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group
        position={[-0.629, 1.307, 4.944]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.192, 1.35, 2]}
      >
        <mesh
          geometry={nodes.building25_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building25_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group
        position={[4.018, 1.307, 4.944]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.192, 1.35, 2]}
      >
        <mesh
          geometry={nodes.building26_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.building26_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <mesh
        geometry={nodes.building10.geometry}
        material={materials.stone}
        position={[0.885, 19.85, -1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[4.276, 1.65, 5.185]}
      />
      <mesh
        geometry={nodes.wood_bars.geometry}
        material={materials["Wood Wall Slits Variation 2"]}
      />
      <mesh
        geometry={nodes.rails11.geometry}
        material={materials["Metal Semirough 01"]}
        position={[4.037, 8.354, 2.881]}
        scale={[-0.037, -0.054, -0.037]}
      />
      <mesh
        geometry={nodes.rails8.geometry}
        material={materials["EEVEE Glass Shader.001"]}
        position={[5.871, 8.387, -3.588]}
        scale={[-0.005, -0.052, -0.037]}
      />
      <mesh
        geometry={nodes.rails1.geometry}
        material={materials["Metal Semirough 01"]}
        position={[4.037, 14.954, 2.881]}
        scale={[-0.037, -0.054, -0.037]}
      />
      <mesh
        geometry={nodes.rails2.geometry}
        material={materials["EEVEE Glass Shader.001"]}
        position={[5.871, 14.987, -3.588]}
        scale={[-0.005, -0.052, -0.037]}
      />
      <mesh
        geometry={nodes.rails5.geometry}
        material={materials["Metal Semirough 01"]}
        position={[-3.47, 11.654, 3.037]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.037, -0.054, -0.037]}
      />
      <mesh
        geometry={nodes.rails6.geometry}
        material={materials["EEVEE Glass Shader.001"]}
        position={[2.999, 11.687, 4.871]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.005, -0.052, -0.037]}
      />
      <mesh
        geometry={nodes.rails7.geometry}
        material={materials["Metal Semirough 01"]}
        position={[-3.47, 18.254, 3.037]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.037, -0.054, -0.037]}
      />
      <mesh
        geometry={nodes.rails9.geometry}
        material={materials["EEVEE Glass Shader.001"]}
        position={[2.999, 18.287, 4.871]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.005, -0.052, -0.037]}
      />
      <mesh
        geometry={nodes.rails10.geometry}
        material={materials["Metal Semirough 01"]}
        position={[-3.47, 5.054, 3.037]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.037, -0.054, -0.037]}
      />
      <mesh
        geometry={nodes.rails12.geometry}
        material={materials["EEVEE Glass Shader.001"]}
        position={[2.999, 5.087, 4.871]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[-0.005, -0.052, -0.037]}
      />
      <mesh
        geometry={nodes.wood.geometry}
        material={materials["Wood Wall Slits Variation 2"]}
        position={[-3.832, 3.439, 5.258]}
        scale={[0.041, 0.027, 0.041]}
      />
    </group>
  );
}

useGLTF.preload("models/building.glb");
