"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/extra building.glb --types -r /src/components 
*/
import { useLayoutEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    extra1: THREE.Mesh;
    extra2: THREE.Mesh;
    extra28: THREE.Mesh;
    extra30: THREE.Mesh;
    extra34_1: THREE.Mesh;
    extra34_2: THREE.Mesh;
    extra33_1: THREE.Mesh;
    extra33_2: THREE.Mesh;
    extra32_1: THREE.Mesh;
    extra32_2: THREE.Mesh;
    extra31_1: THREE.Mesh;
    extra31_2: THREE.Mesh;
    extra36_1: THREE.Mesh;
    extra36_2: THREE.Mesh;
    extra35_1: THREE.Mesh;
    extra35_2: THREE.Mesh;
  };
  materials: {
    ["Metal Semirough 01"]: THREE.MeshStandardMaterial;
    ["EEVEE Glass Shader.001"]: THREE.MeshStandardMaterial;
    ["Wood Wall Slits Variation 2"]: THREE.MeshStandardMaterial;
    ["plaster white irregular"]: THREE.MeshStandardMaterial;
  };
};

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function ExtraBuilding(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/extra building.glb",
  ) as GLTFResult;

  const tl = useRef<GSAPTimeline>();
  const scroll = useScroll();

  useFrame(() => {
    if (!tl.current) return;
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  useLayoutEffect(() => {
    // if (!ref.current) return
    tl.current = gsap.timeline({ defaults: { duration: 1 } });

    Object.values(materials).forEach((material) => {
      material.transparent = true;
      tl.current!.to(
        material,
        {
          opacity: 0,
        },
        0,
      ).to(
        material,
        {
          opacity: 0,
        },
        1,
      );
    });
  }, []);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.extra1.geometry}
        material={materials["Metal Semirough 01"]}
        position={[1.699, 5.939, -28.453]}
        scale={[4.155, 1, 6.446]}
      />
      <mesh
        geometry={nodes.extra2.geometry}
        material={materials["EEVEE Glass Shader.001"]}
        position={[1.699, 5.939, -28.453]}
        scale={[4.155, 1, 6.446]}
      />
      <mesh
        geometry={nodes.extra28.geometry}
        material={materials["Wood Wall Slits Variation 2"]}
        position={[-3.832, 3.439, -18.688]}
        scale={[0.041, 0.027, 0.041]}
      />
      <mesh
        geometry={nodes.extra30.geometry}
        material={materials["plaster white irregular"]}
        position={[0, 0, -23.945]}
      />
      <group position={[7.164, 1.307, -35.332]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.extra34_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.extra34_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group position={[7.164, 1.307, -30.684]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.extra33_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.extra33_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group position={[7.164, 1.307, -26.037]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.extra32_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.extra32_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group position={[7.164, 1.307, -21.389]} scale={[0.192, 1.35, 2]}>
        <mesh
          geometry={nodes.extra31_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.extra31_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group
        position={[4.018, 1.307, -19.001]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.192, 1.35, 2]}
      >
        <mesh
          geometry={nodes.extra36_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.extra36_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
      <group
        position={[-0.629, 1.307, -19.001]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[0.192, 1.35, 2]}
      >
        <mesh
          geometry={nodes.extra35_1.geometry}
          material={materials["Metal Semirough 01"]}
        />
        <mesh
          geometry={nodes.extra35_2.geometry}
          material={materials["EEVEE Glass Shader.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/extra building.glb");
