"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/interior.glb --types 
*/
// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh368_Color_M00_0: THREE.Mesh;
    Mesh369_Color_M00_0: THREE.Mesh;
    Mesh366_BLANC_0: THREE.Mesh;
    Mesh367_BLANC_0: THREE.Mesh;
    Mesh361_Material_8_0: THREE.Mesh;
    Mesh362_Material_8_0: THREE.Mesh;
    Mesh362_Material_8_0001: THREE.Mesh;
    Mesh363_SW_6041_Otter_0: THREE.Mesh;
    Mesh364_Material_8_0: THREE.Mesh;
    Mesh365_BLANC_0: THREE.Mesh;
    Mesh425_CUIR_0: THREE.Mesh;
    Mesh426_Color_M00_0: THREE.Mesh;
    Mesh412_BLANC_0: THREE.Mesh;
    Mesh413_BLANC_0: THREE.Mesh;
    Mesh414_BLANC_0: THREE.Mesh;
    Mesh415_BLANC_0: THREE.Mesh;
    Mesh402_BLANC_0: THREE.Mesh;
    Mesh403_BLANC_0: THREE.Mesh;
    Mesh404_BLANC_0: THREE.Mesh;
    Mesh405_BLANC_0: THREE.Mesh;
    Mesh406_BLANC_0: THREE.Mesh;
    Mesh407_BLANC_0: THREE.Mesh;
    Mesh408_BLANC_0: THREE.Mesh;
    Mesh409_BLANC_0: THREE.Mesh;
    Mesh410_BLANC_0: THREE.Mesh;
    Mesh411_BLANC_0: THREE.Mesh;
    Mesh416_BLANC_0: THREE.Mesh;
    Mesh465_LAMPE_PLAF_0: THREE.Mesh;
    Mesh466_GRIS_BASE_0: THREE.Mesh;
    Mesh467_LAMPE_PLAF_0: THREE.Mesh;
    Mesh468_GRIS_BASE_0: THREE.Mesh;
    Mesh469_LAMPE_PLAF_0: THREE.Mesh;
    Mesh470_GRIS_BASE_0: THREE.Mesh;
    Mesh1_BLANC_0: THREE.Mesh;
    Mesh2_SW_7064_Passive_0: THREE.Mesh;
    Mesh3_SW_7064_Passive_0: THREE.Mesh;
    Mesh4__Silver__0: THREE.Mesh;
    Mesh5_CUIR_0: THREE.Mesh;
    Mesh6__Silver__0: THREE.Mesh;
    Mesh7_CUIR_0: THREE.Mesh;
    Mesh8__Silver__0: THREE.Mesh;
    Mesh9_CUIR_0: THREE.Mesh;
    Mesh113__38_0: THREE.Mesh;
    Mesh114__38_0: THREE.Mesh;
    Mesh115__38_0: THREE.Mesh;
    Mesh116_BLANC_0: THREE.Mesh;
    Mesh116_GRIS_BASE_0: THREE.Mesh;
    Mesh117__38_0: THREE.Mesh;
    Mesh118__Concrete_rough__0: THREE.Mesh;
    Mesh119_BLANC_0: THREE.Mesh;
    Mesh120_Wood__Floor_0: THREE.Mesh;
    Mesh121__CorrogateShiny__0: THREE.Mesh;
    Mesh122_Color_M00_0: THREE.Mesh;
    Mesh123_Wood__Floor_0: THREE.Mesh;
    Mesh125_VITRE_0: THREE.Mesh;
    Mesh126__Silver__0: THREE.Mesh;
    Mesh126_ORANGE_0: THREE.Mesh;
    Mesh127__14_0: THREE.Mesh;
    Mesh128_VITRE_0: THREE.Mesh;
    Mesh129__Silver__0: THREE.Mesh;
    Mesh129_ORANGE_0: THREE.Mesh;
    Mesh129_ORANGE_0001: THREE.Mesh;
    Mesh129_ORANGE_0002: THREE.Mesh;
    Mesh130_BLANC_0: THREE.Mesh;
    Mesh131_BLANC_0: THREE.Mesh;
    Mesh131_LGWasherFront_0: THREE.Mesh;
    Mesh10_BLANC_0: THREE.Mesh;
    Mesh11__Concrete_rough__0: THREE.Mesh;
    Mesh11__DodgerBlue_4_0: THREE.Mesh;
    Mesh11__Silver__0: THREE.Mesh;
    Mesh11__Tomato__0: THREE.Mesh;
    Mesh11_Color_A06_0: THREE.Mesh;
    Mesh11_Color_F09_0: THREE.Mesh;
    Mesh12_Wood__Floor_0: THREE.Mesh;
    Mesh13_Wood__Floor_0: THREE.Mesh;
    Mesh14_Wood__Floor_0: THREE.Mesh;
    Mesh15_Wood__Floor_0: THREE.Mesh;
    Mesh16_Wood__Floor_0: THREE.Mesh;
    Mesh17_Wood__Floor_0: THREE.Mesh;
    Mesh18_Wood__Floor_0: THREE.Mesh;
    Mesh19_Wood__Floor_0: THREE.Mesh;
    Mesh20_BLANC_0: THREE.Mesh;
    Mesh21_BLANC_0: THREE.Mesh;
    Mesh22_GRIS_BASE_0: THREE.Mesh;
    Mesh184_BLANC_0: THREE.Mesh;
    Mesh184_WALL_BLEU_0: THREE.Mesh;
    Mesh185__38_0: THREE.Mesh;
    Mesh185__Silver__0: THREE.Mesh;
    Mesh185_BLANC_0: THREE.Mesh;
    Mesh185_Color_A06_0: THREE.Mesh;
    Mesh185_Color_I08_0: THREE.Mesh;
    Mesh185_Color_M00_0: THREE.Mesh;
    Mesh185_M_1024px_Apple_logo_black_svg_0: THREE.Mesh;
    Mesh185_Translucent_Glass_Gray_0: THREE.Mesh;
    Mesh192__Color_A07_1_0: THREE.Mesh;
    Mesh201__Color_A07_1_0: THREE.Mesh;
    Mesh191__Color_A07_1_0: THREE.Mesh;
    Mesh202__Color_A07_1_0: THREE.Mesh;
    Mesh205__Color_A07_1_0: THREE.Mesh;
    Mesh212__Color_A07_1_0: THREE.Mesh;
    Mesh196__Color_A07_1_0: THREE.Mesh;
    Mesh197__Color_A07_1_0: THREE.Mesh;
    Mesh199__Color_A07_1_0: THREE.Mesh;
    Mesh203__Color_A07_1_0: THREE.Mesh;
    Mesh208__Color_A07_1_0: THREE.Mesh;
    Mesh216__Color_A07_1_0: THREE.Mesh;
    Mesh189__Color_A07_1_0: THREE.Mesh;
    Mesh200__Color_A07_1_0: THREE.Mesh;
    Mesh207__Color_A07_1_0: THREE.Mesh;
    Mesh217__Color_A07_1_0: THREE.Mesh;
    Mesh215__Color_A07_1_0: THREE.Mesh;
    Mesh204__Color_A07_1_0: THREE.Mesh;
    Mesh219__Color_A07_1_0: THREE.Mesh;
    Mesh193__Color_A07_1_0: THREE.Mesh;
    Mesh211__Color_A07_1_0: THREE.Mesh;
    Mesh209__Color_A07_1_0: THREE.Mesh;
    Mesh210__Color_A07_1_0: THREE.Mesh;
    Mesh190__Color_A07_1_0: THREE.Mesh;
    Mesh198__Color_A07_1_0: THREE.Mesh;
    Mesh206__Color_A07_1_0: THREE.Mesh;
    Mesh214__Color_A07_1_0: THREE.Mesh;
    Mesh218__Color_A07_1_0: THREE.Mesh;
    Mesh195__Color_A07_1_0: THREE.Mesh;
    Mesh213__Color_A07_1_0: THREE.Mesh;
    Mesh194__Color_A07_1_0: THREE.Mesh;
    Mesh223__Color_A07_1_0: THREE.Mesh;
    Mesh232__Color_A07_1_0: THREE.Mesh;
    Mesh222__Color_A07_1_0: THREE.Mesh;
    Mesh233__Color_A07_1_0: THREE.Mesh;
    Mesh236__Color_A07_1_0: THREE.Mesh;
    Mesh243__Color_A07_1_0: THREE.Mesh;
    Mesh234__Color_A07_1_0: THREE.Mesh;
    Mesh239__Color_A07_1_0: THREE.Mesh;
    Mesh247__Color_A07_1_0: THREE.Mesh;
    Mesh227__Color_A07_1_0: THREE.Mesh;
    Mesh228__Color_A07_1_0: THREE.Mesh;
    Mesh230__Color_A07_1_0: THREE.Mesh;
    Mesh220__Color_A07_1_0: THREE.Mesh;
    Mesh231__Color_A07_1_0: THREE.Mesh;
    Mesh238__Color_A07_1_0: THREE.Mesh;
    Mesh248__Color_A07_1_0: THREE.Mesh;
    Mesh246__Color_A07_1_0: THREE.Mesh;
    Mesh235__Color_A07_1_0: THREE.Mesh;
    Mesh250__Color_A07_1_0: THREE.Mesh;
    Mesh224__Color_A07_1_0: THREE.Mesh;
    Mesh242__Color_A07_1_0: THREE.Mesh;
    Mesh240__Color_A07_1_0: THREE.Mesh;
    Mesh241__Color_A07_1_0: THREE.Mesh;
    Mesh221__Color_A07_1_0: THREE.Mesh;
    Mesh229__Color_A07_1_0: THREE.Mesh;
    Mesh237__Color_A07_1_0: THREE.Mesh;
    Mesh245__Color_A07_1_0: THREE.Mesh;
    Mesh249__Color_A07_1_0: THREE.Mesh;
    Mesh226__Color_A07_1_0: THREE.Mesh;
    Mesh244__Color_A07_1_0: THREE.Mesh;
    Mesh225__Color_A07_1_0: THREE.Mesh;
    Mesh271_BLANC_0: THREE.Mesh;
    Mesh272_LAMPE_PLAF_0: THREE.Mesh;
    Mesh273_Color_M00_0: THREE.Mesh;
    Mesh274__38_0: THREE.Mesh;
    Mesh276_ORANGE_0: THREE.Mesh;
    Mesh277_ORANGE_0: THREE.Mesh;
    Mesh278_ORANGE_0: THREE.Mesh;
    Mesh279_ORANGE_0: THREE.Mesh;
    Mesh280_ORANGE_0: THREE.Mesh;
    Mesh281_ORANGE_0: THREE.Mesh;
    Mesh282_ORANGE_0: THREE.Mesh;
    Mesh283_ORANGE_0: THREE.Mesh;
    Mesh284_ORANGE_0: THREE.Mesh;
    Mesh285_ORANGE_0: THREE.Mesh;
    Mesh286_ORANGE_0: THREE.Mesh;
    Mesh287_ORANGE_0: THREE.Mesh;
    Mesh296_Color_M00_0: THREE.Mesh;
    Mesh296_Color_M00_0001: THREE.Mesh;
    Mesh309_BLANC_0: THREE.Mesh;
    Mesh301_BLANC_0: THREE.Mesh;
    Mesh307_BLANC_0: THREE.Mesh;
    Mesh305_BLANC_0: THREE.Mesh;
    Mesh302_BLANC_0: THREE.Mesh;
    Mesh304_BLANC_0: THREE.Mesh;
    Mesh313_BLANC_0: THREE.Mesh;
    Mesh318_BLANC_0: THREE.Mesh;
    Mesh308_BLANC_0: THREE.Mesh;
    Mesh317_BLANC_0: THREE.Mesh;
    Mesh299_BLANC_0: THREE.Mesh;
    Mesh311_BLANC_0: THREE.Mesh;
    Mesh315_BLANC_0: THREE.Mesh;
    Mesh298_BLANC_0: THREE.Mesh;
    Mesh300_BLANC_0: THREE.Mesh;
    Mesh306_BLANC_0: THREE.Mesh;
    Mesh316_BLANC_0: THREE.Mesh;
    Mesh312_BLANC_0: THREE.Mesh;
    Mesh310_BLANC_0: THREE.Mesh;
    Mesh303_BLANC_0: THREE.Mesh;
    Mesh314_BLANC_0: THREE.Mesh;
    Mesh297_BLANC_0: THREE.Mesh;
    Mesh319_sapphire_0: THREE.Mesh;
    Mesh320_sapphire_0: THREE.Mesh;
    Mesh321_absolut_vodka_gif_0: THREE.Mesh;
    Mesh322_absolut_vodka_gif_0: THREE.Mesh;
    Mesh323_johnnie_walker_red_label_blended_scotch_whisky_1000ml_1: THREE.Mesh;
    Mesh324_johnnie_walker_red_label_blended_scotch_whisky_1000ml_1: THREE.Mesh;
    Mesh325__38_0: THREE.Mesh;
    Mesh325_M_8444cd48cb1ae53cbd3640ad4f195287_0: THREE.Mesh;
    Mesh23_BLANC_0: THREE.Mesh;
    Mesh24_BLANC_0: THREE.Mesh;
    Mesh347_SW_6041_Otter_0: THREE.Mesh;
    Mesh348_SW_6041_Otter_0: THREE.Mesh;
    Mesh349_FrontColor_0: THREE.Mesh;
    Mesh350_SW_6041_Otter_0: THREE.Mesh;
    Mesh351_SW_6041_Otter_0: THREE.Mesh;
    Mesh352_FrontColor_0: THREE.Mesh;
    Mesh353_Plastic_0: THREE.Mesh;
    Mesh354_BLANC_0: THREE.Mesh;
    Mesh354_FrontColor_0: THREE.Mesh;
    Mesh28_BLANC_0: THREE.Mesh;
    Mesh29_BLANC_0: THREE.Mesh;
    Mesh30_BLANC_0: THREE.Mesh;
    Mesh31_BLANC_0: THREE.Mesh;
    Mesh32_BLANC_0: THREE.Mesh;
    Mesh33_BLANC_0: THREE.Mesh;
    Mesh34_BLANC_0: THREE.Mesh;
    Mesh35_BLANC_0: THREE.Mesh;
    Mesh36_BLANC_0: THREE.Mesh;
    Mesh37_BLANC_0: THREE.Mesh;
    Mesh38_BLANC_0: THREE.Mesh;
    Mesh39_BLANC_0: THREE.Mesh;
    Mesh40_BLANC_0: THREE.Mesh;
    Mesh41_BLANC_0: THREE.Mesh;
    Mesh42_BLANC_0: THREE.Mesh;
    Mesh43_BLANC_0: THREE.Mesh;
    Mesh44_BLANC_0: THREE.Mesh;
    Mesh45_BLANC_0: THREE.Mesh;
    Mesh46_BLANC_0: THREE.Mesh;
    Mesh47_BLANC_0: THREE.Mesh;
    Mesh48_BLANC_0: THREE.Mesh;
    Mesh49_BLANC_0: THREE.Mesh;
    Mesh50_BLANC_0: THREE.Mesh;
    Mesh51_BLANC_0: THREE.Mesh;
    Mesh52_BLANC_0: THREE.Mesh;
    Mesh53_BLANC_0: THREE.Mesh;
    Mesh54_BLANC_0: THREE.Mesh;
    Mesh55_Color_M00_0: THREE.Mesh;
    Mesh55_LAMPE_PLAF_0: THREE.Mesh;
    Mesh25__16_0: THREE.Mesh;
    Mesh26__13_0: THREE.Mesh;
    Mesh27__16_0: THREE.Mesh;
    Mesh56__13_0: THREE.Mesh;
    Mesh57__13_0: THREE.Mesh;
    Mesh357_BLANC_0: THREE.Mesh;
    Mesh358_BLANC_0: THREE.Mesh;
    Mesh359_BLANC_0: THREE.Mesh;
    Mesh360_BLANC_0: THREE.Mesh;
    Mesh360_LAMPE_PLAF_0: THREE.Mesh;
    Mesh355_BLANC_0: THREE.Mesh;
    Mesh355_PREW_ceramic_0: THREE.Mesh;
    Mesh356_Color_M00_0: THREE.Mesh;
    Mesh58_BLANC_0: THREE.Mesh;
    Mesh58_WALL_BLEU_0: THREE.Mesh;
    Mesh59_BLANC_0: THREE.Mesh;
    Mesh59_WALL_BLEU_0: THREE.Mesh;
    Mesh78_Wood__Floor_0: THREE.Mesh;
    Mesh82__Silver__0: THREE.Mesh;
    Mesh82_BLANC_0: THREE.Mesh;
    Mesh82_Color_M00_0: THREE.Mesh;
    Mesh86_BLANC_0: THREE.Mesh;
    Mesh86_Color_A06_0: THREE.Mesh;
    Mesh86_Color_F09_0: THREE.Mesh;
    Mesh86_Color_M00_0: THREE.Mesh;
    Mesh86_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh86_PDM_Concrete_26N_0: THREE.Mesh;
    Mesh86_Translucent_Glass_Gray2_0: THREE.Mesh;
    Mesh86_VITRE_0: THREE.Mesh;
    Mesh80_Wood__Floor_0: THREE.Mesh;
    Mesh81_FrontColor_0: THREE.Mesh;
    Mesh93_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh94_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh87_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh88_BLANC_0: THREE.Mesh;
    Mesh89_BLANC_0: THREE.Mesh;
    Mesh90__5_0: THREE.Mesh;
    Mesh90_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh91_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh92_Metal_Corrogated_Shiny_0: THREE.Mesh;
    Mesh95__Concrete_rough__0: THREE.Mesh;
    Mesh95__Paper__0: THREE.Mesh;
    Mesh95__Stucco__0: THREE.Mesh;
    Mesh95_BLANC_0: THREE.Mesh;
    Mesh85_BLANC_0: THREE.Mesh;
    Mesh96__38_0: THREE.Mesh;
    Mesh96_FrontColor_0: THREE.Mesh;
    Mesh83_BLANC_0: THREE.Mesh;
    Mesh84_BLANC_0: THREE.Mesh;
    Mesh84_Color_M00_0: THREE.Mesh;
    Mesh84_Stainless_Steel_Finish_0: THREE.Mesh;
    Mesh84_Translucent_Glass_Gray_0: THREE.Mesh;
    Mesh97__38_0: THREE.Mesh;
    Mesh98_Color_M00_0: THREE.Mesh;
    Mesh99__38_0: THREE.Mesh;
    Mesh100_Color_M00_0: THREE.Mesh;
    Mesh101__38_0: THREE.Mesh;
    Mesh102_Color_M00_0: THREE.Mesh;
    Mesh103__15_0: THREE.Mesh;
    Mesh103_BLANC_0: THREE.Mesh;
    Mesh438_BLANC_0: THREE.Mesh;
    Mesh439_BLANC_0: THREE.Mesh;
    Mesh440_Color_M00_0: THREE.Mesh;
    Mesh427_BLANC_0: THREE.Mesh;
    Mesh428__38_0: THREE.Mesh;
    Mesh428_BLANC_0: THREE.Mesh;
    Mesh428_Color_M00_0: THREE.Mesh;
    Mesh429__38_0: THREE.Mesh;
    Mesh429_Color_H01_0: THREE.Mesh;
    Mesh429_Color_M00_0: THREE.Mesh;
    Mesh430_BLANC_0: THREE.Mesh;
    Mesh418_Cromado_0: THREE.Mesh;
    Mesh424_BLANC_0: THREE.Mesh;
    Mesh419_BLANC_0: THREE.Mesh;
    Mesh420_BLANC_0: THREE.Mesh;
    Mesh421_BLANC_0: THREE.Mesh;
    Mesh422_BLANC_0: THREE.Mesh;
    Mesh423_BLANC_0: THREE.Mesh;
  };
  materials: {
    Color_M00: THREE.MeshStandardMaterial;
    BLANC: THREE.MeshStandardMaterial;
    Material_8: THREE.MeshStandardMaterial;
    SW_6041_Otter: THREE.MeshStandardMaterial;
    CUIR: THREE.MeshStandardMaterial;
    LAMPE_PLAF: THREE.MeshStandardMaterial;
    GRIS_BASE: THREE.MeshStandardMaterial;
    SW_7064_Passive: THREE.MeshStandardMaterial;
    Silver: THREE.MeshStandardMaterial;
    material_32: THREE.MeshStandardMaterial;
    Concrete_rough: THREE.MeshStandardMaterial;
    Wood__Floor: THREE.MeshStandardMaterial;
    CorrogateShiny: THREE.MeshStandardMaterial;
    VITRE: THREE.MeshStandardMaterial;
    ORANGE: THREE.MeshStandardMaterial;
    material_39: THREE.MeshStandardMaterial;
    LGWasherFront: THREE.MeshStandardMaterial;
    DodgerBlue_4: THREE.MeshStandardMaterial;
    Tomato: THREE.MeshStandardMaterial;
    Color_A06: THREE.MeshStandardMaterial;
    Color_F09: THREE.MeshStandardMaterial;
    WALL_BLEU: THREE.MeshStandardMaterial;
    Color_I08: THREE.MeshStandardMaterial;
    M_1024px_Apple_logo_black_svg: THREE.MeshStandardMaterial;
    Translucent_Glass_Gray: THREE.MeshStandardMaterial;
    Color_A07_1: THREE.MeshStandardMaterial;
    sapphire: THREE.MeshStandardMaterial;
    absolut_vodka_gif: THREE.MeshStandardMaterial;
    johnnie_walker_red_label_blended_scotch_whisky_1000ml_1_562x928: THREE.MeshStandardMaterial;
    M_8444cd48cb1ae53cbd3640ad4f195287: THREE.MeshStandardMaterial;
    FrontColor: THREE.MeshStandardMaterial;
    Plastic: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    material_12: THREE.MeshStandardMaterial;
    PREW_ceramic: THREE.MeshStandardMaterial;
    Metal_Corrogated_Shiny: THREE.MeshStandardMaterial;
    PDM_Concrete_26N: THREE.MeshStandardMaterial;
    Translucent_Glass_Gray2: THREE.MeshStandardMaterial;
    material_29: THREE.MeshStandardMaterial;
    Paper: THREE.MeshStandardMaterial;
    Stucco: THREE.MeshStandardMaterial;
    Stainless_Steel_Finish: THREE.MeshStandardMaterial;
    material_33: THREE.MeshStandardMaterial;
    Color_H01: THREE.MeshStandardMaterial;
    Cromado: THREE.MeshStandardMaterial;
  };
};

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Interior(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("models/interior.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[1.596, 18.449, -2.278]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={1.22}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-7.36, 0, 0]}>
            <mesh
              geometry={nodes.Mesh368_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh369_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh366_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh367_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh361_Material_8_0.geometry}
              material={materials.Material_8}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh362_Material_8_0.geometry}
              material={materials.Material_8}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh362_Material_8_0001.geometry}
              material={materials.Material_8}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh363_SW_6041_Otter_0.geometry}
              material={materials.SW_6041_Otter}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh364_Material_8_0.geometry}
              material={materials.Material_8}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh365_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh425_CUIR_0.geometry}
              material={materials.CUIR}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh426_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh412_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh413_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh414_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh415_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh402_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh403_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh404_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh405_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh406_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh407_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh408_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh409_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh410_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh411_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh416_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh465_LAMPE_PLAF_0.geometry}
              material={materials.LAMPE_PLAF}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh466_GRIS_BASE_0.geometry}
              material={materials.GRIS_BASE}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh467_LAMPE_PLAF_0.geometry}
              material={materials.LAMPE_PLAF}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh468_GRIS_BASE_0.geometry}
              material={materials.GRIS_BASE}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh469_LAMPE_PLAF_0.geometry}
              material={materials.LAMPE_PLAF}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh470_GRIS_BASE_0.geometry}
              material={materials.GRIS_BASE}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh1_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh2_SW_7064_Passive_0.geometry}
              material={materials.SW_7064_Passive}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh3_SW_7064_Passive_0.geometry}
              material={materials.SW_7064_Passive}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh4__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh5_CUIR_0.geometry}
              material={materials.CUIR}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh6__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh7_CUIR_0.geometry}
              material={materials.CUIR}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh8__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh9_CUIR_0.geometry}
              material={materials.CUIR}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh113__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh114__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh115__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh116_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh116_GRIS_BASE_0.geometry}
              material={materials.GRIS_BASE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh117__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh118__Concrete_rough__0.geometry}
              material={materials.Concrete_rough}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh119_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh120_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh121__CorrogateShiny__0.geometry}
              material={materials.CorrogateShiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh122_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh123_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh125_VITRE_0.geometry}
              material={materials.VITRE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh126__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh126_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh127__14_0.geometry}
              material={materials.material_39}
              position={[6.405, -0.123, -0.284]}
            />
            <mesh
              geometry={nodes.Mesh128_VITRE_0.geometry}
              material={materials.VITRE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh129__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh129_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh129_ORANGE_0001.geometry}
              material={materials.ORANGE}
              position={[9.911, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh129_ORANGE_0002.geometry}
              material={materials.ORANGE}
              position={[9.721, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh130_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh131_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh131_LGWasherFront_0.geometry}
              material={materials.LGWasherFront}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh10_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh11__Concrete_rough__0.geometry}
              material={materials.Concrete_rough}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh11__DodgerBlue_4_0.geometry}
              material={materials.DodgerBlue_4}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh11__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh11__Tomato__0.geometry}
              material={materials.Tomato}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh11_Color_A06_0.geometry}
              material={materials.Color_A06}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh11_Color_F09_0.geometry}
              material={materials.Color_F09}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh12_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh13_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh14_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh15_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh16_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh17_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh18_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh19_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh20_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh21_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh22_GRIS_BASE_0.geometry}
              material={materials.GRIS_BASE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh184_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh184_WALL_BLEU_0.geometry}
              material={materials.WALL_BLEU}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh185__38_0.geometry}
              material={materials.material_32}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185__Silver__0.geometry}
              material={materials.Silver}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185_Color_A06_0.geometry}
              material={materials.Color_A06}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185_Color_I08_0.geometry}
              material={materials.Color_I08}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185_M_1024px_Apple_logo_black_svg_0.geometry}
              material={materials.M_1024px_Apple_logo_black_svg}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh185_Translucent_Glass_Gray_0.geometry}
              material={materials.Translucent_Glass_Gray}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh192__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh201__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh191__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh202__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh205__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh212__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh196__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh197__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh199__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh203__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh208__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh216__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh189__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh200__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh207__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh217__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh215__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh204__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh219__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh193__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh211__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh209__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh210__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh190__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh198__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh206__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh214__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh218__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh195__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh213__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh194__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh223__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh232__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh222__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh233__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh236__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh243__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh234__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh239__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh247__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh227__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh228__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh230__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh220__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh231__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh238__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh248__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh246__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh235__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh250__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh224__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh242__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh240__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh241__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh221__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh229__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh237__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh245__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh249__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh226__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh244__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh225__Color_A07_1_0.geometry}
              material={materials.Color_A07_1}
              position={[10.482, -2.716, -0.632]}
            />
            <mesh
              geometry={nodes.Mesh271_BLANC_0.geometry}
              material={materials.BLANC}
              position={[5.807, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh272_LAMPE_PLAF_0.geometry}
              material={materials.LAMPE_PLAF}
              position={[5.807, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh273_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[5.807, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh274__38_0.geometry}
              material={materials.material_32}
              position={[5.807, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh276_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[8.757, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh277_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[8.352, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh278_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[5.83, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh279_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[8.352, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh280_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[5.83, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh281_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[5.433, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh282_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[5.021, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh283_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[5.83, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh284_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[5.021, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh285_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[6.741, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh286_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[6.741, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh287_ORANGE_0.geometry}
              material={materials.ORANGE}
              position={[6.741, -0.173, -0.812]}
            />
            <mesh
              geometry={nodes.Mesh296_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[7.28, -0.173, -0.07]}
              rotation={[0, -1.571, 0]}
              scale={[3.422, 1, 1]}
            />
            <mesh
              geometry={nodes.Mesh296_Color_M00_0001.geometry}
              material={materials.Color_M00}
              position={[6.263, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh309_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh301_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh307_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh305_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh302_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh304_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh313_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh318_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh308_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh317_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh299_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh311_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh315_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh298_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh300_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh306_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh316_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh312_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh310_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh303_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh314_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh297_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -1.413]}
              scale={[1, 1, 0.663]}
            />
            <mesh
              geometry={nodes.Mesh319_sapphire_0.geometry}
              material={materials.sapphire}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh320_sapphire_0.geometry}
              material={materials.sapphire}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh321_absolut_vodka_gif_0.geometry}
              material={materials.absolut_vodka_gif}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh322_absolut_vodka_gif_0.geometry}
              material={materials.absolut_vodka_gif}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={
                nodes
                  .Mesh323_johnnie_walker_red_label_blended_scotch_whisky_1000ml_1
                  .geometry
              }
              material={
                materials.johnnie_walker_red_label_blended_scotch_whisky_1000ml_1_562x928
              }
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={
                nodes
                  .Mesh324_johnnie_walker_red_label_blended_scotch_whisky_1000ml_1
                  .geometry
              }
              material={
                materials.johnnie_walker_red_label_blended_scotch_whisky_1000ml_1_562x928
              }
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh325__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={
                nodes.Mesh325_M_8444cd48cb1ae53cbd3640ad4f195287_0.geometry
              }
              material={materials.M_8444cd48cb1ae53cbd3640ad4f195287}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh23_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh24_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh347_SW_6041_Otter_0.geometry}
              material={materials.SW_6041_Otter}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh348_SW_6041_Otter_0.geometry}
              material={materials.SW_6041_Otter}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh349_FrontColor_0.geometry}
              material={materials.FrontColor}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh350_SW_6041_Otter_0.geometry}
              material={materials.SW_6041_Otter}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh351_SW_6041_Otter_0.geometry}
              material={materials.SW_6041_Otter}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh352_FrontColor_0.geometry}
              material={materials.FrontColor}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh353_Plastic_0.geometry}
              material={materials.Plastic}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh354_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh354_FrontColor_0.geometry}
              material={materials.FrontColor}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh28_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh29_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh30_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh31_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh32_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh33_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh34_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh35_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh36_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh37_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh38_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh39_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh40_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh41_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh42_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh43_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh44_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh45_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh46_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh47_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh48_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh49_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh50_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh51_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh52_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh53_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh54_BLANC_0.geometry}
              material={materials.BLANC}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh55_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh55_LAMPE_PLAF_0.geometry}
              material={materials.LAMPE_PLAF}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh25__16_0.geometry}
              material={materials.material}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh26__13_0.geometry}
              material={materials.material_12}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh27__16_0.geometry}
              material={materials.material}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh56__13_0.geometry}
              material={materials.material_12}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh57__13_0.geometry}
              material={materials.material_12}
              position={[10.87, -2.716, -1.773]}
              rotation={[0, 1.571, 0]}
            />
            <mesh
              geometry={nodes.Mesh357_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh358_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh359_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh360_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh360_LAMPE_PLAF_0.geometry}
              material={materials.LAMPE_PLAF}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh355_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh355_PREW_ceramic_0.geometry}
              material={materials.PREW_ceramic}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh356_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[9.498, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh58_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh58_WALL_BLEU_0.geometry}
              material={materials.WALL_BLEU}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh59_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh59_WALL_BLEU_0.geometry}
              material={materials.WALL_BLEU}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh78_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh82__Silver__0.geometry}
              material={materials.Silver}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh82_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh82_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_Color_A06_0.geometry}
              material={materials.Color_A06}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_Color_F09_0.geometry}
              material={materials.Color_F09}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_PDM_Concrete_26N_0.geometry}
              material={materials.PDM_Concrete_26N}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_Translucent_Glass_Gray2_0.geometry}
              material={materials.Translucent_Glass_Gray2}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh86_VITRE_0.geometry}
              material={materials.VITRE}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh80_Wood__Floor_0.geometry}
              material={materials.Wood__Floor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh81_FrontColor_0.geometry}
              material={materials.FrontColor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh93_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh94_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh87_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh88_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh89_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh90__5_0.geometry}
              material={materials.material_29}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh90_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh91_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh92_Metal_Corrogated_Shiny_0.geometry}
              material={materials.Metal_Corrogated_Shiny}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh95__Concrete_rough__0.geometry}
              material={materials.Concrete_rough}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh95__Paper__0.geometry}
              material={materials.Paper}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh95__Stucco__0.geometry}
              material={materials.Stucco}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh95_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh85_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh96__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh96_FrontColor_0.geometry}
              material={materials.FrontColor}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh83_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh84_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh84_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh84_Stainless_Steel_Finish_0.geometry}
              material={materials.Stainless_Steel_Finish}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh84_Translucent_Glass_Gray_0.geometry}
              material={materials.Translucent_Glass_Gray}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh97__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh98_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh99__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh100_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh101__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh102_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh103__15_0.geometry}
              material={materials.material_33}
              position={[6.228, -0.173, -0.415]}
            />
            <mesh
              geometry={nodes.Mesh103_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.415]}
            />
            <mesh
              geometry={nodes.Mesh438_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh439_BLANC_0.geometry}
              material={materials.BLANC}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh440_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[9.493, -2.716, -1.323]}
              rotation={[-Math.PI, 0, -Math.PI]}
            />
            <mesh
              geometry={nodes.Mesh427_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh428__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh428_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh428_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh429__38_0.geometry}
              material={materials.material_32}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh429_Color_H01_0.geometry}
              material={materials.Color_H01}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh429_Color_M00_0.geometry}
              material={materials.Color_M00}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh430_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.146]}
            />
            <mesh
              geometry={nodes.Mesh418_Cromado_0.geometry}
              material={materials.Cromado}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh424_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh419_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh420_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh421_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh422_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
            <mesh
              geometry={nodes.Mesh423_BLANC_0.geometry}
              material={materials.BLANC}
              position={[6.228, -0.173, -0.416]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/interior.glb");
