# .github/workflows/keep_alive.yml

name: Keep alive cron job
on:
  schedule:
    - cron: "0 12 * * *" # daily https://crontab.guru/#0_12_*_*_*
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call endpoint to keep the database alive
        run: |
          curl --request PUT \
            --url 'https://tanjingren.me/api/keep-alive'
